@startuml

title __HOUSE's Class Diagram__\n

  namespace academy.mindswap {
    namespace sims {
      namespace house {
        class academy.mindswap.sims.house.House {
            - MAX_DIRTINESS_LEVEL : int
            - dirtinessLevel : int
            - rooms : ArrayList<Room>
            + House()
            + addDivision()
            + getDirtinessLevel()
            + getRoom()
            + iterator()
            + listRooms()
            + useRoom()
            ~ cleanHouse()
        }
      }
    }
  }
  

  namespace academy.mindswap {
    namespace sims {
      namespace house {
        class academy.mindswap.sims.house.Maid {
            - PAYMENT_FEE : double
            + cleanHouse()
        }
      }
    }
  }
  

  namespace academy.mindswap {
    namespace sims {
      namespace house {
        class academy.mindswap.sims.house.Room {
            + Room()
            + getRoomCleanlinessDecrease()
            + getRoomType()
            + toString()
        }
      }
    }
  }
  

  namespace academy.mindswap {
    namespace sims {
      namespace house {
        enum RoomType {
          BATHROOM
          BEDROOM
          CINEMA
          GYM
          KITCHEN
          LIBRARY
          LIVING_ROOM
          OFFICE
          SWIMMING_POOL
          houseCleanlinessDecrease
        }
      }
    }
  }
  

  academy.mindswap.sims.house.House .up.|> java.lang.Iterable
  academy.mindswap.sims.house.Room o-- academy.mindswap.sims.house.RoomType : roomType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
